In [6]:
import numpy as  np

arr = np.random.randint(1,100,size =(10,5)) #sample = 10 ,feature = 5

In [7]:
arr.shape

(10, 5)

In [8]:
b = arr.reshape(5,10)

b.shape
b.ndim
b

array([[ 2, 39, 35, 43, 59, 83, 74, 17, 56, 31],
       [78, 33, 87, 39, 38, 79, 21, 85, 43, 75],
       [44,  9, 90,  6, 97, 29, 15, 10, 39, 59],
       [11, 98, 94, 71,  2, 59, 83, 81, 25, 69],
       [55, 36,  6, 91, 49, 45,  8,  7, 22, 92]], dtype=int32)

In [9]:
flattern = b.flatten()

print(flattern)
print('ndim=',flattern.ndim)
flattern


#colowm

column_wise_flatterning = np.ravel(b,order= 'F')

print(column_wise_flatterning)

                                   

[ 2 39 35 43 59 83 74 17 56 31 78 33 87 39 38 79 21 85 43 75 44  9 90  6
 97 29 15 10 39 59 11 98 94 71  2 59 83 81 25 69 55 36  6 91 49 45  8  7
 22 92]
ndim= 1
[ 2 78 44 11 55 39 33  9 98 36 35 87 90 94  6 43 39  6 71 91 59 38 97  2
 49 83 79 29 59 45 74 21 15 83  8 17 85 10 81  7 56 43 39 25 22 31 75 59
 69 92]


In [10]:
a = np.random.randint(1,10, size = (2,3))
b = np.random.randint(20,30, size = (2,3))


print(a)
print(b)

[[6 2 9]
 [7 1 7]]
[[28 24 23]
 [27 20 23]]


# concatenate

In [11]:
con_row = np.concatenate((a,b),axis= 0) #row wise

print(con_row)

con_col = np.concatenate((a,b),axis = 1) #colum wise

print(con_col)

[[ 6  2  9]
 [ 7  1  7]
 [28 24 23]
 [27 20 23]]
[[ 6  2  9 28 24 23]
 [ 7  1  7 27 20 23]]


In [12]:
# Transpose

mat = np.array([[10,20,30],
                [40,26,90] ])

tranpose = mat.T

print(tranpose)

[[10 40]
 [20 26]
 [30 90]]


In [13]:
#array split

a = np.random.randint(1,10, size=(10,))

print(a)

splitted_array = np.array_split(a,3)

print(splitted_array)

[2 8 4 4 3 4 6 9 4 3]
[array([2, 8, 4, 4], dtype=int32), array([3, 4, 6], dtype=int32), array([9, 4, 3], dtype=int32)]


## arithmetic operator and mathematical functions

In [14]:
x = np.array([19,8,34,16,100])

y = np.array([3,5,6,7,3])

add = x+y

print('add=',add)

sub = x - y

print('sub=',mul)

mul = x*y

print('mul=',mul)


div = x/y

print('div=',div)

reminder = x %y

print('reminder=',reminder)

add= [ 22  13  40  23 103]


NameError: name 'mul' is not defined

In [ ]:
#mathematcial  function

#trigonometry

#sin,cos,tan takes values in radian

sin_val = np.sin(x)

print(sin_val)

cos_val = np.cos(x)

print(cos_val)

deg_con = np.rad2deg(x)

print('deg_con=',deg_con)

In [ ]:
#log
print(x)
base_10_log_val = np.log10(x)

print(base_10_log_val)


two_times_division = np.log2(x)

print(two_times_division)

sqrt = np.sqrt(x)

print(sqrt)

# Logical Function

In [ ]:
# comparison - >,< , >= ,<= , == , !=

x = np.array([ 10 , 8 , 16 , 100 ])
y = np.array([ 2 , 3 ,16  ,5 ])

greater_than = x>y

print(greater_than)

equal = x==y

print(equal)

# all () -> shob true kina
# any() -> jekono ekta true ase kina

print(np.all(greater_than))

print(np.any(equal))


# sorting 

In [ ]:
#inplace
x = np.array([ 10 , 8 , 16 , 100 ])

z = x.copy()

print(z)

z.sort()

print(z)


In [ ]:
# copy sorting
print(x)
sort_arr = np.sort(x)

print(sort_arr)

print(x)

In [ ]:
# 2d array sorting
mat = np.array([[10,3,5],[8,4,9]])

# horizon axis = 1

hor_sort = np.sort(mat,axis=1)
print(hor_sort)

vert_sort = np.sort(mat,axis=0)
print(vert_sort)


# searching 

In [ ]:
x = [34,5434,16,6,56]
print(x)

In [17]:
#np.where

index = np.where(x==16)

print(index)

index = np.where(x>6)

print(index)

arr = np.where(mat>8,mat,0) # returns array
print(arr)

(array([3]),)
(array([0, 1, 2, 3, 4]),)
[[10 20 30]
 [40 26 90]]


In [19]:
x = np.array([ 10,100 , 8 , 16 , 100,2 ])

maximum_value_indx = np.argmax(x)
minimum_value_indx = np.argmin(x)

print(maximum_value_indx)
print(minimum_value_indx)

1
5


# counting in ndarray

In [25]:
a = np.random.randint(1,100 , size = (100,))
print(a)

[40 92 11 15 31 57 14 96  8 38 69 12 98 69 16 42 66 85 10  6 68 73 43 24
 28 91 77 65 62 58  8 32 65 89 97 95 79 11 62 58  5 89 38 20 34 10  8 84
 97 67 37 10 75 49 61 20 41 64  5 22 58  9 54 35 39 56 79 32 41 25 42 16
 35 89 87 71 71 55  2 41 39 92 86 97 14 30 70 36 99 90 63 63 59  2 80 92
 57 46 37 92]


In [30]:
value_great_than_60 = np.count_nonzero(a > 40)

print(value_great_than_60)

59


In [33]:
unique_value,count = np.unique(a,return_counts = True)

print(unique_value)
print(count)

[ 2  5  6  8  9 10 11 12 14 15 16 20 22 24 25 28 30 31 32 34 35 36 37 38
 39 40 41 42 43 46 49 54 55 56 57 58 59 61 62 63 64 65 66 67 68 69 70 71
 73 75 77 79 80 84 85 86 87 89 90 91 92 95 96 97 98 99]
[2 2 1 3 1 3 2 1 2 1 2 2 1 1 1 1 1 1 2 1 2 1 2 2 2 1 3 2 1 1 1 1 1 1 2 3 1
 1 2 2 1 2 1 1 1 2 1 2 1 1 1 2 1 1 1 1 1 3 1 1 4 1 1 3 1 1]


# statistical function

In [35]:
#data load

data = np.genfromtxt('student_scores.csv' ,delimiter=',',skip_header=1)

print(data)


[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [36]:
# statistics
math_marks = data[::,:1]

print(math_marks.T)

max_math_marks = np.max(math_marks)
print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

average_math_marks = np.mean(math_marks)
print(average_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks)

# standard deviation

std_math_marks = np.std(math_marks)
print(std_math_marks)




[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.5
13.788672887555204


In [37]:

study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])

correlation = np.corrcoef(data)

print("Correlation Matrix:\n", correlation)


Correlation Matrix:
 [[1.         0.99859154]
 [0.99859154 1.        ]]


# Linear Algebra with NumPy

In [38]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# a er column and b er row same length hote hobe
dot_product = np.dot(A,B)
print(dot_product)


# trace
print(np.trace(B))


#

[[ 58  64]
 [139 154]]
17


In [39]:
sq_mat = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]
         ])

det_of_sq = np.linalg.det(sq_mat)

rank_sq = np.linalg.matrix_rank(sq_mat)

print(det_of_sq)

print(rank_sq)

-9.51619735392994e-16
2


In [40]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A,B))

[[19 22]
 [43 50]]
