In [2]:
arr = [1,2,3]

print(arr*5)

arr = [x*5 for x in arr]

print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [5]:
import numpy as np

arr1 = np.array([1,2,3])

arr1 = arr1*5
print(arr1)

[ 5 10 15]


### Ndarray


In [6]:
import numpy as np

# 1d array
arr1 = np.array([1,2,3,4,5])


# 2d array
arr2 = np.array([ [1,2,3], # row1
                  [4,5,6] #row2
                ])

#3d array

arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6]  ], #row2

    #2nd floor

     [[1,2,3], # row1
      [4,5,6]  ], #row2


    #3rd floor
      [[1,2,3], # row1
      [4,5,6]  ] #row2


])


## Array attrubutes

#ndarray data type


import numpy as np

#upcasted to float
arr = np.array([1, 3, 4])
print(arr.dtype)

#upcasted to string 
arr = np.array([1, 5, 2, 4, 3, 2])
print(arr.dtype)

In [8]:
arr = np.array([2,34,5.5])

print(arr.dtype)

arr = np.array([3,4,6,'3'])
print(arr.dtype)

float64
<U21


##selecting a data type for an array

In [15]:
arr = np.array([2,3,4,5],dtype= np.int8)

print(arr.dtype)

arr = np.array([3,45,6 ,'string'],dtype ='<U32')

print(arr.dtype)

int8
<U32


#ndarray creation from existing data

In [22]:
# lst = [13,34,234,23,34.3]

# arr = np.array(lst,dtype = np.int32)

# print(arr)
# print(type(arr))
# print(arr.dtype)


mixed_lst = [234,True, 'Hello',23.3]

arr = np.array(mixed_lst)

print(arr)
print(type(arr))
print(arr.dtype)



matix = [ [1,2,3],
          [4,5,6] ]


arr = np.array(matix)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

['234' 'True' 'Hello' '23.3']
<class 'numpy.ndarray'>
<U32
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [23]:
#tuple

tpl = (10,20,30)

arr = np.array(tpl,dtype=np.int32)
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


int32
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


In [24]:
#set

st = { 1, 2, 3 }

arr = np.array(list(st))
# print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


[1 2 3]
<class 'numpy.ndarray'>
int16
(3,)
1


In [25]:
# dictionary

dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }

keys = dc.keys()
values = dc.values()
items = dc.items()



In [26]:
#keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


# array creation with random values

In [28]:
# np.random.rand(shape)

arr = np.random.rand(2,3) # 0 ->1

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.02727504 0.35608064 0.8582398 ]
 [0.35561524 0.31332035 0.58560185]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [29]:
# np.random.randint(start,end, shape)

arr = np.random.randint(1,10 , (2,3))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[3 8 1]
 [2 8 3]]
<class 'numpy.ndarray'>
int32
(2, 3)
2
6


In [30]:
# np.random.uniform(start,end, shape)

arr = np.random.uniform(50,100, (3,3,4))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[75.94487957 58.69975749 98.38957304 93.13564127]
  [82.89114051 65.88357503 53.47766497 66.38049888]
  [83.15530551 74.28810783 71.24444682 93.10415681]]

 [[76.83611982 74.19102485 89.69387498 78.26891509]
  [53.96523081 84.48591367 90.86492986 79.62694745]
  [70.78767613 76.20709585 55.01974576 76.75364176]]

 [[75.35679537 75.90005111 86.29146744 61.84965297]
  [50.44310109 97.57244005 94.59340534 98.4492701 ]
  [80.1660215  86.33257226 97.40933246 73.74620288]]]
<class 'numpy.ndarray'>
float64
(3, 3, 4)
3
36


array creation with range functions

In [31]:
# np.arange(first , end , step ) -> similar to range function

arr = np.arange(1 , 10 ,1 )
mat = arr.reshape(3,3)

print(arr)
print(mat)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [32]:
# np.linspace(start , end(included) , koita)

arr = np.linspace(0, 4 ,6)


print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[0.  0.8 1.6 2.4 3.2 4. ]
<class 'numpy.ndarray'>
float64
(6,)
1
6


In [33]:
# np.logspace(start , end(included) , koita )

arr = np.logspace(0 , 4 ,6, base =2)

print(arr)


[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


indexing and slicing

In [5]:
#indexing

arr2 = [ [1,2,3],
         [5,6,7] ]

print(arr2)

# arr1[2] = 100

# print(arr1)
print(arr2[0][2])

arr2[0][2] = 234

print(arr2)




[[1, 2, 3], [5, 6, 7]]
3
[[1, 2, 234], [5, 6, 7]]


In [7]:
 #slicing
#1d = arr[start:end:step]

arr1 = [[1,3,5,6 ],
        [3,6,7,2] ]

arr1_mod = arr1[1:4]

print(arr1_mod)

[[3, 6, 7, 2]]


In [11]:
import numpy as np

# create a 2D array
arr2 = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print("Original array:")
print(arr2)


# --------------------
# getting rows
# --------------------
row_0 = arr2[0:1, :]   # first row (2D)
row_1 = arr2[1:, :]    # from second row onward

print("\nFirst row:")
print(row_0)

print("\nRemaining rows:")
print(row_1)


# --------------------
# getting columns
# --------------------
col_0 = arr2[:, 0]     # first column (1D)
col_1 = arr2[:, 1]     # second column (1D)

print("\nFirst column:")
print(col_0)

print("\nSecond column:")
print(col_1)


# --------------------
# getting a portion
# --------------------
portion = arr2[:, 0:2]  # first two columns of all rows

print("\nPortion (first 2 columns):")
print(portion)

Original array:
[[1 2]
 [3 4]
 [5 6]]

First row:
[[1 2]]

Remaining rows:
[[3 4]
 [5 6]]

First column:
[1 3 5]

Second column:
[2 4 6]

Portion (first 2 columns):
[[1 2]
 [3 4]
 [5 6]]
